//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32")]
        public double setDisplay_camPitch {
            get {
                return ((double)(this["setDisplay_camPitch"]));
            }
            set {
                this["setDisplay_camPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM GPS...")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public int setPort_baudRate {
            get {
                return ((int)(this["setPort_baudRate"]));
            }
            set {
                this["setPort_baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point setWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["setWindow_Location"]));
            }
            set {
                this["setWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
        public global::System.Drawing.Size setWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["setWindow_Size"]));
            }
            set {
                this["setWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Maximized {
            get {
                return ((bool)(this["setWindow_Maximized"]));
            }
            set {
                this["setWindow_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLoadFields {
            get {
                return ((bool)(this["AutoLoadFields"]));
            }
            set {
                this["AutoLoadFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Minimized {
            get {
                return ((bool)(this["setWindow_Minimized"]));
            }
            set {
                this["setWindow_Minimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM Section...")]
        public string setPort_portNameMachine {
            get {
                return ((string)(this["setPort_portNameMachine"]));
            }
            set {
                this["setPort_portNameMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasMachineConnected {
            get {
                return ((bool)(this["setPort_wasMachineConnected"]));
            }
            set {
                this["setPort_wasMachineConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isMetric {
            get {
                return ((bool)(this["setMenu_isMetric"]));
            }
            set {
                this["setMenu_isMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isGridOn {
            get {
                return ((bool)(this["setMenu_isGridOn"]));
            }
            set {
                this["setMenu_isGridOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isLightbarOn {
            get {
                return ((bool)(this["setMenu_isLightbarOn"]));
            }
            set {
                this["setMenu_isLightbarOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setF_CurrentDir {
            get {
                return ((string)(this["setF_CurrentDir"]));
            }
            set {
                this["setF_CurrentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM AS")]
        public string setPort_portNameAutoSteer {
            get {
                return ((string)(this["setPort_portNameAutoSteer"]));
            }
            set {
                this["setPort_portNameAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasAutoSteerConnected {
            get {
                return ((bool)(this["setPort_wasAutoSteerConnected"]));
            }
            set {
                this["setPort_wasAutoSteerConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setIMU_pitchZeroX16 {
            get {
                return ((int)(this["setIMU_pitchZeroX16"]));
            }
            set {
                this["setIMU_pitchZeroX16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setIMU_rollZeroX16 {
            get {
                return ((int)(this["setIMU_rollZeroX16"]));
            }
            set {
                this["setIMU_rollZeroX16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isLogNMEA {
            get {
                return ((bool)(this["setMenu_isLogNMEA"]));
            }
            set {
                this["setMenu_isLogNMEA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setF_minFixStep {
            get {
                return ((double)(this["setF_minFixStep"]));
            }
            set {
                this["setF_minFixStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTotalArea {
            get {
                return ((double)(this["setF_UserTotalArea"]));
            }
            set {
                this["setF_UserTotalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTripAlarm {
            get {
                return ((double)(this["setF_UserTripAlarm"]));
            }
            set {
                this["setF_UserTripAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSideGuideLines {
            get {
                return ((bool)(this["setMenu_isSideGuideLines"]));
            }
            set {
                this["setMenu_isSideGuideLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isPureOn {
            get {
                return ((bool)(this["setMenu_isPureOn"]));
            }
            set {
                this["setMenu_isPureOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keyhole.txt")]
        public string setAS_youTurnShape {
            get {
                return ((string)(this["setAS_youTurnShape"]));
            }
            set {
                this["setAS_youTurnShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int setIP_thisPort {
            get {
                return ((int)(this["setIP_thisPort"]));
            }
            set {
                this["setIP_thisPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.255")]
        public string setIP_autoSteerIP {
            get {
                return ((string)(this["setIP_autoSteerIP"]));
            }
            set {
                this["setIP_autoSteerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public int setIP_autoSteerPort {
            get {
                return ((int)(this["setIP_autoSteerPort"]));
            }
            set {
                this["setIP_autoSteerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSimulatorOn {
            get {
                return ((bool)(this["setMenu_isSimulatorOn"]));
            }
            set {
                this["setMenu_isSimulatorOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSkyOn {
            get {
                return ((bool)(this["setMenu_isSkyOn"]));
            }
            set {
                this["setMenu_isSkyOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string setF_culture {
            get {
                return ((string)(this["setF_culture"]));
            }
            set {
                this["setF_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68wESU")]
        public string setIMU_UID {
            get {
                return ((string)(this["setIMU_UID"]));
            }
            set {
                this["setIMU_UID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromAutoSteer {
            get {
                return ((bool)(this["setIMU_isRollFromAutoSteer"]));
            }
            set {
                this["setIMU_isRollFromAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingCorrectionFromAutoSteer {
            get {
                return ((bool)(this["setIMU_isHeadingCorrectionFromAutoSteer"]));
            }
            set {
                this["setIMU_isHeadingCorrectionFromAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int setPort_NMEAHz {
            get {
                return ((int)(this["setPort_NMEAHz"]));
            }
            set {
                this["setPort_NMEAHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromAVR {
            get {
                return ((bool)(this["setIMU_isRollFromAVR"]));
            }
            set {
                this["setIMU_isRollFromAVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int setDisplay_lightbarCmPerPixel {
            get {
                return ((int)(this["setDisplay_lightbarCmPerPixel"]));
            }
            set {
                this["setDisplay_lightbarCmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isOn {
            get {
                return ((bool)(this["setUDP_isOn"]));
            }
            set {
                this["setUDP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GGA")]
        public string setGPS_fixFromWhichSentence {
            get {
                return ((string)(this["setGPS_fixFromWhichSentence"]));
            }
            set {
                this["setGPS_fixFromWhichSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fix")]
        public string setGPS_headingFromWhichSource {
            get {
                return ((string)(this["setGPS_headingFromWhichSource"]));
            }
            set {
                this["setGPS_headingFromWhichSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53.4360564")]
        public double setGPS_SimLatitude {
            get {
                return ((double)(this["setGPS_SimLatitude"]));
            }
            set {
                this["setGPS_SimLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111.160047")]
        public double setGPS_SimLongitude {
            get {
                return ((double)(this["setGPS_SimLongitude"]));
            }
            set {
                this["setGPS_SimLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69.75.31.235")]
        public string setNTRIP_casterIP {
            get {
                return ((string)(this["setNTRIP_casterIP"]));
            }
            set {
                this["setNTRIP_casterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2101")]
        public int setNTRIP_casterPort {
            get {
                return ((int)(this["setNTRIP_casterPort"]));
            }
            set {
                this["setNTRIP_casterPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AZU1")]
        public string setNTRIP_mount {
            get {
                return ((string)(this["setNTRIP_mount"]));
            }
            set {
                this["setNTRIP_mount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userName {
            get {
                return ((string)(this["setNTRIP_userName"]));
            }
            set {
                this["setNTRIP_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userPassword {
            get {
                return ((string)(this["setNTRIP_userPassword"]));
            }
            set {
                this["setNTRIP_userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isOn {
            get {
                return ((bool)(this["setNTRIP_isOn"]));
            }
            set {
                this["setNTRIP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int setNTRIP_sendGGAInterval {
            get {
                return ((int)(this["setNTRIP_sendGGAInterval"]));
            }
            set {
                this["setNTRIP_sendGGAInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setNTRIP_sendToUDPPort {
            get {
                return ((int)(this["setNTRIP_sendToUDPPort"]));
            }
            set {
                this["setNTRIP_sendToUDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public double setNTRIP_manualLat {
            get {
                return ((double)(this["setNTRIP_manualLat"]));
            }
            set {
                this["setNTRIP_manualLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111")]
        public double setNTRIP_manualLon {
            get {
                return ((double)(this["setNTRIP_manualLon"]));
            }
            set {
                this["setNTRIP_manualLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.rtk2go.com")]
        public string setNTRIP_casterURL {
            get {
                return ((string)(this["setNTRIP_casterURL"]));
            }
            set {
                this["setNTRIP_casterURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isGGAManual {
            get {
                return ((bool)(this["setNTRIP_isGGAManual"]));
            }
            set {
                this["setNTRIP_isGGAManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int setAS_snapDistance {
            get {
                return ((int)(this["setAS_snapDistance"]));
            }
            set {
                this["setAS_snapDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setDistance_TreeSpacing {
            get {
                return ((double)(this["setDistance_TreeSpacing"]));
            }
            set {
                this["setDistance_TreeSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromOGI {
            get {
                return ((bool)(this["setIMU_isRollFromOGI"]));
            }
            set {
                this["setIMU_isRollFromOGI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int setDisplay_lineWidth {
            get {
                return ((int)(this["setDisplay_lineWidth"]));
            }
            set {
                this["setDisplay_lineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97, 600")]
        public global::System.Drawing.Point setDisplay_panelSimLocation {
            get {
                return ((global::System.Drawing.Point)(this["setDisplay_panelSimLocation"]));
            }
            set {
                this["setDisplay_panelSimLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double setTram_eqWidth {
            get {
                return ((double)(this["setTram_eqWidth"]));
            }
            set {
                this["setTram_eqWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public double setTram_wheelSpacing {
            get {
                return ((double)(this["setTram_wheelSpacing"]));
            }
            set {
                this["setTram_wheelSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setTram_snapAdj {
            get {
                return ((double)(this["setTram_snapAdj"]));
            }
            set {
                this["setTram_snapAdj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setTram_passes {
            get {
                return ((int)(this["setTram_passes"]));
            }
            set {
                this["setTram_passes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setTram_offset {
            get {
                return ((double)(this["setTram_offset"]));
            }
            set {
                this["setTram_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setMenu_isOGLZoomOn {
            get {
                return ((int)(this["setMenu_isOGLZoomOn"]));
            }
            set {
                this["setMenu_isOGLZoomOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isUTurnAlwaysOn {
            get {
                return ((bool)(this["setMenu_isUTurnAlwaysOn"]));
            }
            set {
                this["setMenu_isUTurnAlwaysOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isCompassOn {
            get {
                return ((bool)(this["setMenu_isCompassOn"]));
            }
            set {
                this["setMenu_isCompassOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSpeedoOn {
            get {
                return ((bool)(this["setMenu_isSpeedoOn"]));
            }
            set {
                this["setMenu_isSpeedoOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isTCP {
            get {
                return ((bool)(this["setNTRIP_isTCP"]));
            }
            set {
                this["setNTRIP_isTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 230, 230")]
        public global::System.Drawing.Color setDisplay_colorDayMode {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorDayMode"]));
            }
            set {
                this["setDisplay_colorDayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 60")]
        public global::System.Drawing.Color setDisplay_colorNightMode {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorNightMode"]));
            }
            set {
                this["setDisplay_colorNightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 151, 160")]
        public global::System.Drawing.Color setDisplay_colorSectionsDay {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorSectionsDay"]));
            }
            set {
                this["setDisplay_colorSectionsDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 90, 90")]
        public global::System.Drawing.Color setDisplay_colorFieldDay {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorFieldDay"]));
            }
            set {
                this["setDisplay_colorFieldDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplay_isSimple {
            get {
                return ((bool)(this["setDisplay_isSimple"]));
            }
            set {
                this["setDisplay_isSimple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isDayMode {
            get {
                return ((bool)(this["setDisplay_isDayMode"]));
            }
            set {
                this["setDisplay_isDayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 100, 100")]
        public global::System.Drawing.Color setDisplay_colorSectionsNight {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorSectionsNight"]));
            }
            set {
                this["setDisplay_colorSectionsNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 60")]
        public global::System.Drawing.Color setDisplay_colorFieldNight {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorFieldNight"]));
            }
            set {
                this["setDisplay_colorFieldNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isAutoDayNight {
            get {
                return ((bool)(this["setDisplay_isAutoDayNight"]));
            }
            set {
                this["setDisplay_isAutoDayNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2898748,-1003858,-22138,-2387,-4530790,-2562841,-2895106,-2568981,-12705503,-120" +
            "54528,-11384832,-13679872,-16767718,-16774804,-15794140,-12707256")]
        public string setDisplay_customColors {
            get {
                return ((string)(this["setDisplay_customColors"]));
            }
            set {
                this["setDisplay_customColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isTermsOn {
            get {
                return ((bool)(this["setDisplay_isTermsOn"]));
            }
            set {
                this["setDisplay_isTermsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setGPS_isRTK {
            get {
                return ((bool)(this["setGPS_isRTK"]));
            }
            set {
                this["setGPS_isRTK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingCorrectionFromBrick {
            get {
                return ((bool)(this["setIMU_isHeadingCorrectionFromBrick"]));
            }
            set {
                this["setIMU_isHeadingCorrectionFromBrick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplay_isStartFullScreen {
            get {
                return ((bool)(this["setDisplay_isStartFullScreen"]));
            }
            set {
                this["setDisplay_isStartFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isInterAppOn {
            get {
                return ((bool)(this["setUDP_isInterAppOn"]));
            }
            set {
                this["setUDP_isInterAppOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplay_isKeyboardOn {
            get {
                return ((bool)(this["setDisplay_isKeyboardOn"]));
            }
            set {
                this["setDisplay_isKeyboardOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isHTTP10 {
            get {
                return ((bool)(this["setNTRIP_isHTTP10"]));
            }
            set {
                this["setNTRIP_isHTTP10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double setIMU_fusionWeight {
            get {
                return ((double)(this["setIMU_fusionWeight"]));
            }
            set {
                this["setIMU_fusionWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double Tram_wheelWidth {
            get {
                return ((double)(this["Tram_wheelWidth"]));
            }
            set {
                this["Tram_wheelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawBackBuffer {
            get {
                return ((bool)(this["DrawBackBuffer"]));
            }
            set {
                this["DrawBackBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-0.0,0.0
-0.0,1.0
-0.1,2.0
-0.35,3.0
-0.7,4.0
-1.2,5.0
-1.6,6.0
-1.8,7.0
-1.9,8.0
-1.8,9.0
-1.6,10.0
-1.22,10.9
-0.7,11.8
-0.0,12.7
1.0,13.6
2.0,14.25
3.0,14.7
4.0,14.93
5.0,15.0
6,14.93
7,14.7
8,14.25
9,13.6
10,12.7
10.7,11.8
11.2,10.9
11.6,10
11.8,9.0
11.9,8.0
11.8,7.0
11.6,6.0
11.2,5.0
10.7,4.0
10.35,3.0
10.1,2.0
10.0,1.0
10.0,0.0")]
        public string KeyHole {
            get {
                return ((string)(this["KeyHole"]));
            }
            set {
                this["KeyHole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0.0,0.0
0.0,1.0
0.0,2.0
0.0,2.99999
0.06156,3.78216
0.24471,4.54507
0.54496,5.26994
0.95491,5.93891
1.46445,6.53552
2.06106,7.04507
2.73003,7.45502
3.45490,7.75528
4.21781,7.93844
4.99998,8.00000
5.78215,7.93844
6.54506,7.75529
7.26993,7.45504
7.93891,7.04510
8.53552,6.53555
9.04507,5.93895
9.45502,5.26997
9.75527,4.54511
9.93844,3.78220
10.0000,3.00003
10.0,2.0
10.0,1.0
10.0,0")]
        public string SemiCircle {
            get {
                return ((string)(this["SemiCircle"]));
            }
            set {
                this["SemiCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000000000005,0.0928477204695962\r\n0.000000000093,0.185638169563126\r\n0.0000000000" +
            "5,0.27848589060883\r\n0.000000000056,0.371333303149218\r\n0.000000000043,0.464180716" +
            "553766\r\n0.000000000003,0.556970704185564\r\n0.000000000057,0.64981811730206\r\n0.000" +
            "000000046,0.742665530418555\r\n0.000000000005,0.835512943823103\r\n0.000000000006,0." +
            "928360280317363\r\n0.00000000005,1.0211503451475\r\n0.0000000000,1.11399775797595\r\n0" +
            ".00000000008,1.20684517166855\r\n0.00000000009,1.29969250816281\r\n0.00000000002,1.3" +
            "9248257270489\r\n0.0000000000,1.48532998668555\r\n0.00000000003,1.5781774000901\r\n0.0" +
            "0000000007,1.67102473687241\r\n0.00000000009,1.76387215056501\r\n0.00000000005,1.856" +
            "66221568321\r\n0.0000000000,1.94950962937581\r\n0.00000000004,2.04235696615812\r\n0.00" +
            "000000003,2.13520437985073\r\n0.00000000003,2.22799444525697\r\n0.00000000007,2.3208" +
            "4185894958\r\n0.00000000009,2.41368919601994\r\n0.00000000007,2.50653660971255\r\n0.00" +
            "000000004,2.59938402426931\r\n0.00000000001,2.69217408967555\r\n0.00000000001,2.7850" +
            "2142703398\r\n0.00000000002,2.87786884072658\r\n0.00000000008,2.97071625470723\r\n0.00" +
            "00000000,3.06350632068959\r\n0.0000000000,3.15635365804801\r\n0.0000000000,3.2492010" +
            "7260477\r\n0.0000000000,3.34204848658543\r\n0.0000000000,3.4348958242319\r\n0.00000000" +
            "00,3.52768589050231\r\n0.0000000000,3.62053330477102\r\n0.0000000000,3.7133807190397" +
            "3\r\n0.0000000000,3.8062280566862\r\n0.0000000000,3.89901812324466\r\n0.0000000000,3.9" +
            "9186476841049\r\n0.00270430138609812,4.08471033683227\r\n0.00417994051323193,4.17755" +
            "452000469\r\n0.00634034357208115,4.27033981639694\r\n0.00949384054321268,4.363122882" +
            "39081\r\n0.0136060576045438,4.45584644545803\r\n0.0188141025764203,4.54856754595575\r" +
            "\n0.0255286528338477,4.64117056582806\r\n0.033681089708622,4.73359830888085\r\n0.0433" +
            "05915656724,4.82596539621683\r\n0.0543686279341195,4.9181572067333\r\n0.066869097186" +
            "7767,5.01011639300807\r\n0.0810129200811263,5.10189984186575\r\n0.0965601263086883,5" +
            ".19339339424151\r\n0.11371631176175,5.28465393782411\r\n0.132481218704428,5.37556677" +
            "546476\r\n0.152820731230556,5.46618933322424\r\n0.174768835856261,5.55640683646735\r\n" +
            "0.198257043051333,5.64621943959078\r\n0.223319597085784,5.73562706568423\r\n0.250093" +
            "218744057,5.82451471082189\r\n0.27844105758162,5.91294003064322\r\n0.308328740802582" +
            ",6.00084575377215\r\n0.339722022894699,6.08823195769508\r\n0.372655148362027,6.17509" +
            "856521366\r\n0.407127859342661,6.26133087946714\r\n0.443071666630448,6.3469290554283" +
            "\r\n0.480520943039284,6.43195036274489\r\n0.519612151509706,6.51616510235866\r\n0.5601" +
            "40211189114,6.59974578001429\r\n0.602139108449608,6.68257762222879\r\n0.645574598625" +
            "101,6.76466070591245\r\n0.690446681553562,6.84599503164136\r\n0.736720983250879,6.92" +
            "652332775142\r\n0.78443174908527,7.0062455181965\r\n0.833510488932412,7.085161755356" +
            "9\r\n0.8840936660389,7.16304233931021\r\n0.936010443894161,7.24005970061915\r\n0.98929" +
            "5066534164,7.31621376093317\r\n1.04391303233108,7.39138990116595\r\n1.09983009622276" +
            ",7.46558819880389\r\n1.15701201365112,7.53880873046923\r\n1.21549302874215,7.6110514" +
            "1925166\r\n1.275204395454,7.68220172268713\r\n1.33631733598287,7.75225925651223\r\n1.3" +
            "9859213862035,7.82122455909898\r\n1.46209716345258,7.88904012805241\r\n1.52676417911" +
            "733,7.9558208143419\r\n1.59262717249079,8.02145184448445\r\n1.65958328119284,8.08587" +
            "610121264\r\n1.72766687823541,8.14915085590252\r\n1.79684359116468,8.21121883688999\r" +
            "\n1.86721589527085,8.27196511744756\r\n1.93864707041759,8.33150470150105\r\n2.0111027" +
            "4316089,8.38978031796244\r\n2.08454854012876,8.44673469631984\r\n2.15898471891305,8." +
            "50248253228179\r\n2.23441089409816,8.55685178098922\r\n2.31075883340366,8.6099572934" +
            "1153\r\n2.3879940350037,8.66168445075046\r\n2.46625321950267,8.71191824677577\r\n2.545" +
            "36542262028,8.76077376405189\r\n2.62533077248632,8.80830835172931\r\n2.7060805231669" +
            "4,8.85440746590371\r\n2.78764891925623,8.89907102995284\r\n2.87000171596206,8.942299" +
            "12107505\r\n2.95307055359436,8.98414924224143\r\n3.03688941931736,9.0245066179526\r\n3" +
            ".12145805564723,9.06325655365224\r\n3.20667398720376,9.10051397491558\r\n3.292537213" +
            "69889,9.13627888404708\r\n3.37901361964053,9.17060870480309\r\n3.46606870340086,9.20" +
            "338881780926\r\n3.55370246548397,9.23461922277752\r\n3.64188078964162,9.264357346632" +
            "85\r\n3.73053493015602,9.29248864403062\r\n3.81973337610729,9.31901296316664\r\n3.9093" +
            "733947934,9.34393053390762\r\n3.99942074104418,9.36724143345188\r\n4.08987567324364," +
            "9.389060357508\r\n4.18070368938586,9.4092726884299\r\n4.27187054509282,9.42787850111" +
            "152\r\n4.36334199676064,9.4448778739034\r\n4.45511817255511,9.4603281545158\r\n4.54716" +
            "431449878,9.47400002642553\r\n4.63941231928721,9.48606568802418\r\n4.73189643160448," +
            "9.49652506268951\r\n4.82451391882058,9.50537838230461\r\n4.9172990251155,9.512625567" +
            "9428\r\n5.01018326196723,9.51826677428883\r\n5.10316650131798,9.52224465334441\r\n5.19" +
            "618038275751,9.52461670692839\r\n5.2892246493601,9.52526823789197\r\n5.3822650572878" +
            "1,9.52419932314544\r\n5.4753019922263,9.52158200812397\r\n5.56826670894385,9.5173017" +
            "4921127\r\n5.66112521926802,9.51147332017839\r\n5.75387726758732,9.5039820238765\r\n5." +
            "84648873734748,9.49488528665447\r\n5.93892525636471,9.48412583627208\r\n6.0311524514" +
            "4704,9.4716464010652\r\n6.12310209126823,9.45756183056295\r\n6.21484266521447,9.4418" +
            "7197238504\r\n6.3062714398276,9.42457705582205\r\n6.39738854397555,9.40573442973645\r" +
            "\n6.48815960522251,9.38528682304023\r\n6.57855037863233,9.36323431120341\r\n6.6685609" +
            "9363105,9.33963424308844\r\n6.7580883312189,9.31431480399103\r\n6.84720165170327,9.2" +
            "8761993096094\r\n6.93586658309844,9.25949235089379\r\n7.02411749785822,9.22998933660" +
            "589\r\n7.11192040889038,9.19922566129221\r\n7.19924094393912,9.16714405328862\r\n7.286" +
            "11360396616,9.1338591319695\r\n7.37246977203161,9.0993137031571\r\n7.4583781950235,9" +
            ".06362230902747\r\n7.54370137970587,9.02655586436438\r\n7.62850820178068,8.988286259" +
            "63023\r\n7.71273030031561,8.94887099693194\r\n7.796436036315,8.90825257445063\r\n7.879" +
            "48830372282,8.86637395038889\r\n7.96192160362681,8.82334974498525\r\n8.0437700523652" +
            ",8.77912253246695\r\n8.1249654177296,8.73380716380339\r\n8.20543882621446,8.68723174" +
            "651582\r\n8.28525902308749,8.63951082393248\r\n8.36432301816285,8.59052992992346\r\n8." +
            "44252794976254,8.54023194520496\r\n8.51983931577265,8.48850225097872\r\n8.5962232579" +
            "5089,8.43551296814992\r\n8.67157652830349,8.38103493257571\r\n8.74596800210034,8.325" +
            "24003731092\r\n8.81936356294917,8.26818570553585\r\n8.89176321094001,8.2098719392668" +
            "5\r\n8.96313270169482,8.15029881282175\r\n9.03343779083557,8.08946640368692\r\n9.10254" +
            "137138807,8.02731767121718\r\n9.1704776885945,7.96385253677392\r\n9.23714400813256,7" +
            ".89907123195215\r\n9.30257483166607,7.8330883758382\r\n9.36659842253522,7.7656749581" +
            "0976\r\n9.42931815722365,7.69711749090801\r\n9.49069966225133,7.62735870170468\r\n9.55" +
            "070869288016,7.55639866827421\r\n9.60937962273419,7.4842946605524\r\n9.6666442187228" +
            "5,7.4111615297967\r\n9.72246797992044,7.33688465519247\r\n9.77685103442075,7.2615213" +
            "8473801\r\n9.82979363878947,7.1851864158702\r\n9.88126142050074,7.1078224757727\r\n9.9" +
            "3122039136412,7.02954433850462\r\n9.97967042274571,6.95029465520349\r\n10.0265772697" +
            "994,6.87007350220349\r\n10.0719413182108,6.78905292522786\r\n10.115590959072,6.70706" +
            "126195259\r\n10.1576291835408,6.62421297908369\r\n10.1980904916969,6.54062269541942\r" +
            "\n10.2369406399363,6.45629048959839\r\n10.274145254059,6.37115908909233\r\n10.3097389" +
            "643986,6.28540046098583\r\n10.3436531530971,6.1989574116773\r\n10.3758878193444,6.11" +
            "182993972645\r\n10.406443348718,6.02419009172068\r\n10.4353194838242,5.9359231699350" +
            "6\r\n10.4624822367786,5.84714394727649\r\n10.4880685855074,5.75785211725602\r\n10.5119" +
            "76052884,5.66816260717723\r\n10.534444351121,5.57807487924421\r\n10.5554736081681,5." +
            "48764628289552\r\n10.5752694199717,5.39693370553189\r\n10.5937632965335,5.3059373003" +
            "978\r\n10.6109896113334,5.21471433886931\r\n10.627290938424,5.12332140329848\r\n10.642" +
            "5987886353,5.03175864721783\r\n10.656947406021,4.94002599285292\r\n10.6704738974295," +
            "4.8481804822892\r\n10.6835550823714,4.75627862039235\r\n10.6959853639284,4.664263519" +
            "18552\r\n10.7079360940467,4.57219214297974\r\n10.7190646979536,4.48000791057516\r\n10." +
            "729371303617,4.38776817025813\r\n10.7385816968184,4.29535883872189\r\n10.74679886855" +
            "39,4.20289438324853\r\n10.7538857115431,4.1103177611765\r\n10.7600135772103,4.017685" +
            "93768096\r\n10.7651824651054,3.92499891362607\r\n10.769186907556,3.83225714759304\r\n1" +
            "0.7722323718385,3.73946018042457\r\n10.7741135184101,3.64666582071651\r\n10.77506993" +
            "17678,3.55381618296271\r\n10.7749990051968,3.4609688461804\r\n10.773832378341,3.3681" +
            "8131103623\r\n10.7716725275348,3.2753386516669\r\n10.7683827315075,3.18255587113407\r" +
            "\n10.7640999682216,3.08983266237267\r\n10.7588584823609,2.99716894962464\r\n10.752487" +
            "0501091,2.90456511542504\r\n10.7451568948865,2.81202077723881\r\n10.7366625485707,2." +
            "71953639451131\r\n10.7272096070538,2.62716885608352\r\n10.7167980706601,2.5349181608" +
            "0325\r\n10.7052568434506,2.44284204208439\r\n10.6927568925862,2.35082541851473\r\n10.6" +
            "79093005952,2.25898344784067\r\n10.6645048969487,2.16731559255434\r\n10.648924075182" +
            ",2.07582200676438\r\n10.6322476780736,1.98444557176308\r\n10.6146129418978,1.8933006" +
            "7734616\r\n10.5958486417038,1.80238770806505\r\n10.5761601185287,1.71164885445974\r\n1" +
            "0.5556501051463,1.62108388637546\r\n10.5341817515083,1.53075045945166\r\n10.51209737" +
            "57317,1.44059045860353\r\n10.4897049238037,1.35048849708215\r\n10.4670043948781,1.26" +
            "044457402334\r\n10.4441327680874,1.17045838293816\r\n10.4213979890407,1.080414537653" +
            "8\r\n10.3990055258786,0.990312576996577\r\n10.376921133827,0.900152578452879\r\n10.355" +
            "4870034671,0.809819078075434\r\n10.3348058692654,0.71931184542143\r\n10.314774996737" +
            "4,0.628631110645627\r\n10.2955657380096,0.53783383949931\r\n10.2769724968475,0.44686" +
            "3142277321\r\n10.2591664967257,0.355718637308752\r\n10.2420110159056,0.2645153256388" +
            "79\r\n10.2256426476718,0.173080857359964\r\n10.2100617780162,0.0815872770430191\r\n10." +
            "1951311711685,-0.0100798056837797\r\n10.181022307817,-0.101806076782791\r\n10.167529" +
            "5907913,-0.193648425095011\r\n10.1548583609122,-0.285664659216315\r\n10.142837779418" +
            "6,-0.377682350888407\r\n10.1316044404596,-0.469873851171239\r\n10.1210217498503,-0.5" +
            "62066808428753\r\n10.1112605469636,-0.654433651783404\r\n10.102286971811,-0.74680225" +
            "8313622\r\n10.0939980342607,-0.839287096165682\r\n10.0864623513966,-0.93183096943353" +
            "6\r\n10.0796115630063,-1.02437637687442\r\n10.0735481463067,-1.11703824435163\r\n10.06" +
            "8169624099,-1.20970164657797\r\n10.0635786023057,-1.30242416084234\r\n10.04963823087" +
            "84,-1.39514813208139\r\n10.0364853598836,-1.48793121564653\r\n10.0254017255737,-1.58" +
            "07731819591\r\n10.02518574825612,-1.67355848987348\r\n10.02500400284385,-1.766401913" +
            "16074\r\n10.0100000815061,-1.85918829493863\r\n10.0100000062098,-1.95203202442677\r\n1" +
            "0.010000080217,-2.04481809913961\r\n10.0100000011436,-2.13766113902763\r\n10.0100000" +
            "266355,-2.23044644665396\r\n10.00000099767,-2.32328871916742\r\n10.000000008303,-2.4" +
            "1607364281841\r\n10.000000223471,-2.50885826055657\r\n10.000000911794,-2.60169984231" +
            "77\r\n10.00000064433,-2.6944836926813\r\n10.000000131139,-2.78726715906956\r\n10.00000" +
            "0823923,-2.88005031896888\r\n10.000000270621,-2.97283309518091\r\n10.000000760091,-3" +
            ".06555813913126\r\n10.000000167937,-3.15834022516707\r\n10.000000883936,-3.251121850" +
            "60531\r\n10.000000086488,-3.34384582098021\r\n10,-3.43662713964145")]
        public string WideReturn {
            get {
                return ((string)(this["WideReturn"]));
            }
            set {
                this["WideReturn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.22460785746389E-05,0.126697717111741\r\n-4.47607565901982E-05,0.253373451607725\r\n" +
            "-4.87713883251535E-06,0.380071168396992\r\n3.73665844332394E-05,0.506768886133955\r" +
            "\n-1.83554062885716E-05,0.633251678882555\r\n2.07719628141881E-05,0.75994939435561\r" +
            "\n6.30131146602974E-05,0.886647112679322\r\n-2.3245665407389E-05,1.01332284835816\r\n" +
            "1.58796311562109E-05,1.14002056433039\r\n8.94059166116035E-05,1.26652533896386\r\n-7" +
            ".24087990511899E-07,1.39320107509135\r\n4.15130799880021E-05,1.5198987917898\r\n8.37" +
            "495503287081E-05,1.64659650738226\r\n-5.62881428384467E-06,1.77327224310453\r\n3.660" +
            "60819137824E-05,1.89996995844698\r\n-1.91254450483471E-05,2.02645275167693\r\n1.9992" +
            "6317622305E-05,2.15315046766939\r\n6.22246768816692E-05,2.27984818455074\r\n-2.40433" +
            "733797529E-05,2.40652391975887\r\n1.50724254242407E-05,2.53322163522144\r\n8.8589696" +
            "3308917E-05,2.65972640942234\r\n1.56580937003327E-06,2.78640214320755\r\n4.067848515" +
            "97337E-05,2.91309986033494\r\n8.29055231262173E-05,3.03979757741841\r\n-6.4819586414" +
            "8698E-06,3.16647331169838\r\n3.57435576473226E-05,3.29317102655062\r\n-1.99969570957" +
            "414E-05,3.4196538183576\r\n1.91117088540985E-05,3.54635153485024\r\n6.13342505467426" +
            "E-05,3.67304925122215\r\n-2.49430548572503E-05,3.79972498595959\r\n1.4163698882337E-" +
            "05,3.92642270198002\r\n8.7671853293818E-05,4.0529274747385\r\n6.38282388968038E-07,4" +
            ".1796032099765\r\n3.9742120201304E-05,4.30630092470915\r\n8.195992639607E-05,4.43299" +
            "864033102\r\n-7.43654100288809E-06,4.55967437318791\r\n6.60668002067124E-05,4.686179" +
            "14816819\r\n-2.09702514706879E-05,4.81285488086735\r\n1.81289167198681E-05,4.9395525" +
            "9685032\r\n6.03420208889571E-05,5.06625031471324\r\n-2.59442729591465E-05,5.19292604" +
            "802783\r\n1.31533919534921E-05,5.31962376161506\r\n8.66519957517167E-05,5.4461285358" +
            "4528\r\n-3.90297327477421E-07,5.57280426870822\r\n3.87042863369057E-05,5.69950198296" +
            "965\r\n8.16665076999811E-05,5.82619969903305\r\n-8.49373879837022E-06,5.952875434353" +
            "59\r\n6.50008740436061E-05,6.07938020695853\r\n-2.20456796777843E-05,6.2060559391484" +
            "7\r\n1.70446217233194E-05,6.33275365372732\r\n5.92487384946776E-05,6.45945137016711\r" +
            "\n-2.70467917781053E-05,6.58612710202038\r\n1.20412933248718E-05,6.71282481806979\r\n" +
            "8.55309373357284E-05,6.8393295898862\r\n-1.5208944054798E-06,6.96600532323054\r\n3.7" +
            "5640304032937E-05,7.09270303795369\r\n8.05175097452741E-05,7.21940075263248\r\n-9.65" +
            "200304490014E-06,7.34607648748204\r\n6.38335091122095E-05,7.47258125864455\r\n0.0001" +
            "06030354824776,7.59927897293984\r\n0.00108116660750463,7.72593763437418\r\n0.0032539" +
            "7568113261,7.85260127898057\r\n0.00636361146028384,7.979226068791\r\n0.0104054130616" +
            "281,8.10581222414903\r\n0.0156448836535966,8.23240399224882\r\n0.0218203991537619,8." +
            "3589577126203\r\n0.0290893072548166,8.48530297708353\r\n0.0372671092140341,8.6118038" +
            "7732244\r\n0.0465405504659172,8.73809730117558\r\n0.0569330234697151,8.8641827481963" +
            "6\r\n0.0685178759195038,8.99046789063399\r\n0.0808339065190642,9.11647861247152\r\n0.0" +
            "943672885248375,9.24249649958144\r\n0.108896498257891,9.36828386885786\r\n0.12467399" +
            "1430701,9.49388568539837\r\n0.14128514354038,9.61942767123437\r\n0.158853905490239,9" +
            ".74493254084857\r\n0.17767525042729,9.87025156227611\r\n0.19749052569759,9.995340076" +
            "39368\r\n0.218300055220673,10.1201979661722\r\n0.240193159948028,10.2450416411398\r\n0" +
            ".263081790550718,10.3696545123766\r\n0.287090760171979,10.4940596583671\r\n0.3122260" +
            "41298604,10.618256141808\r\n0.33821846380571,10.7422007102833\r\n0.365200341158156,1" +
            "0.8659153924135\r\n0.393308468434419,10.9894213529295\r\n0.42253707090652,11.1127196" +
            "858392\r\n0.453015729394273,11.2358330451223\r\n0.48493600728813,11.3583987603273\r\n0" +
            ".517976908002444,11.4807572501836\r\n0.552301203643961,11.6027380301744\r\n0.5879089" +
            "05921111,11.7243412324624\r\n0.624794454355038,11.8455684498116\r\n0.663120546430798" +
            ",11.96624951667\r\n0.702730208006327,12.0865536736685\r\n0.743623483257028,12.206481" +
            "0699959\r\n0.785803123788822,12.3260310218021\r\n0.829305836105397,12.4450091646534\r" +
            "\n0.874221977354015,12.5636336319554\r\n0.920456618516741,12.6816879098573\r\n0.96816" +
            "9462608837,12.7990027885958\r\n1.01733058616933,12.9157706919365\r\n1.0679448005227," +
            "13.0319899597432\r\n1.11987764632256,13.1476394396748\r\n1.17328882905853,13.2625501" +
            "854541\r\n1.22801868175586,13.3768914305934\r\n1.28422922206155,13.4904933642228\r\n1." +
            "34176095423151,13.6035249232402\r\n1.40077351817501,13.7158173722692\r\n1.4610116828" +
            "8706,13.827322374203\r\n1.52289282645906,13.9379185707651\r\n1.58612719798271,14.047" +
            "7516669838\r\n1.65068295785497,14.1570145006246\r\n1.71662402000982,14.2653212826172" +
            "\r\n1.78378593282479,14.3728430064684\r\n1.85233306696364,14.4794087463504\r\n1.922201" +
            "77886756,14.5854041489297\r\n1.99332542004003,14.6904203471565\r\n2.06569985024479,1" +
            "4.794459857836\r\n2.13930418798806,14.897708550378\r\n2.21445155355844,14.9998344709" +
            "941\r\n2.29081968079928,15.1011754582867\r\n2.36860315324906,15.2013689537953\r\n2.447" +
            "92817884331,15.3004415235391\r\n2.52853829407945,15.3983436096658\r\n2.6107188374845" +
            "3,15.4949349886934\r\n2.69447367111435,15.590213430523\r\n2.77983256779563,15.683988" +
            "4278304\r\n2.86676391738619,15.7764533877855\r\n2.95533535404971,15.8672202399434\r\n3" +
            ".04550941916059,15.9564873871887\r\n3.13732284395034,16.0440587787783\r\n3.230777481" +
            "37136,16.1299335379506\r\n3.32606087271614,16.2137573158848\r\n3.42301867482115,16.2" +
            "956926438883\r\n3.52168078792379,16.3755497493674\r\n3.62175851499857,16.45346998370" +
            "24\r\n3.72354146473467,16.5293129462019\r\n3.82690409197631,16.6030499397839\r\n3.9315" +
            "8149149521,16.6746378061077\r\n4.0378392310571,16.744120138207\r\n4.14541473958342,1" +
            "6.8114507179258\r\n4.25431372539518,16.8766218753218\r\n4.3646644460494,16.939661040" +
            "1579\r\n4.47610408215666,17.0003060283716\r\n4.58886250812329,17.0587980205858\r\n4.70" +
            "270971151896,17.1148959397099\r\n4.81777674606823,17.1686238821112\r\n4.933930830795" +
            "83,17.219960757283\r\n5.051011085075,17.2690709348973\r\n5.16904645517703,17.3157671" +
            "207471\r\n5.28806722594414,17.3598604058035\r\n5.40801353258847,17.4017279815159\r\n5." +
            "52878430159847,17.4411562224977\r\n5.65027667205624,17.477936448803\r\n5.77243100213" +
            "461,17.5124434065989\r\n5.89544048965956,17.5443214699629\r\n6.01901007082145,17.573" +
            "7148518588\r\n6.14300593032053,17.6006059825938\r\n6.26769398001813,17.6250352276329" +
            "\r\n6.39284169210333,17.6467648593078\r\n6.51838488347636,17.6661808353407\r\n6.644254" +
            "24074619,17.6828798508651\r\n6.77041964463808,17.6970460544571\r\n6.89691055230853,1" +
            "7.7084999323587\r\n7.02353376690498,17.7175873080232\r\n7.15035106115767,17.72393593" +
            "11239\r\n7.27733121423888,17.7277339375003\r\n7.404310194902,17.7291481632628\r\n7.531" +
            "2191966291,17.7277752725709\r\n7.65815841657393,17.7238344794636\r\n7.78496415069547" +
            ",17.7174829694919\r\n7.91169992511258,17.7083484266715\r\n8.03803709838141,17.696760" +
            "1824339\r\n8.16427247316444,17.6825812693279\r\n8.29014122917495,17.6657597750354\r\n8" +
            ".41561121702694,17.6464887798922\r\n8.54058287973266,17.6245623492659\r\n8.665155267" +
            "1823,17.6001804594064\r\n8.78922905407905,17.5731386294667\r\n8.91264005898629,17.54" +
            "36078488005\r\n9.0354863694966,17.5117892203352\r\n9.15770229818452,17.4772908906333" +
            "\r\n9.27912265868967,17.4402784581251\r\n9.3996149494779,17.4007290251568\r\n9.5193454" +
            "7268337,17.3584786007636\r\n9.63804913099361,17.313480128043\r\n9.75566135650151,17." +
            "2661168102871\r\n9.87221398179742,17.2161945099825\r\n9.98760953426828,17.1635059137" +
            "176\r\n10.1018170900444,17.1082450225321\r\n10.2147020154228,17.050382246943\r\n10.326" +
            "2655040475,16.9899196172218\r\n10.4365715059153,16.927254529775\r\n10.5453894095919," +
            "16.8621549532996\r\n10.6527177179497,16.794617782661\r\n10.7584283627519,16.72462914" +
            "73277\r\n10.8625199138671,16.652185512066\r\n10.9649558625057,16.5774718925414\r\n11.0" +
            "656066486614,16.5004712718867\r\n11.1646996528723,16.4214124391664\r\n11.26187501175" +
            "14,16.3400448251335\r\n11.3572351624648,16.256585976723\r\n11.4506446759681,16.17100" +
            "92932464\r\n11.5421375347623,16.083124166266\r\n11.6314795083441,15.9934802394291\r\n1" +
            "1.7190000486385,15.9017368073491\r\n11.804371449698,15.8082373173566\r\n11.887659944" +
            "5413,15.7125982095338\r\n11.9687691303598,15.6153978141929\r\n12.0474986716491,15.51" +
            "62063866239\r\n12.1240793808975,15.4152588843456\r\n12.1984752463602,15.312744801565" +
            "9\r\n12.2705540211769,15.2086426508074\r\n12.340222491875,15.1027434518479\r\n12.40741" +
            "39306422,14.9954306220465\r\n12.4721276079752,14.8867034465361\r\n12.5343938853935,1" +
            "4.7763676969928\r\n12.5944101905332,14.6648511364739\r\n12.6518120300804,14.55189551" +
            "98102\r\n12.7065389150881,14.4378890543805\r\n12.7587892837249,14.3224687911413\r\n12." +
            "808363826933,14.2059967744401\r\n12.8552587589976,14.0884710010448\r\n12.89963939578" +
            "52,13.9697211260016\r\n12.9412762497506,13.8503036401675\r\n12.9802346564977,13.7298" +
            "333258259\r\n13.0164892704651,13.6085057770234\r\n13.0498682514477,13.4864886953428\r" +
            "\n13.0805355255608,13.3636109894273\r\n13.1087183199303,13.2401078751285\r\n13.133864" +
            "84576,13.1160876522117\r\n13.1563632403901,12.9916135424272\r\n13.1758606150663,12.8" +
            "664299574361\r\n13.1926780925016,12.7409855272053\r\n13.2065565026323,12.61523764034" +
            "25\r\n13.2174962449933,12.4891862051135\r\n13.225913872932,12.3627021141696\r\n13.2313" +
            "286807066,12.2363005056573\r\n13.2339083478257,12.1098105193842\r\n13.2336399702157," +
            "11.9832306030096\r\n13.2305326708817,11.8565616801955\r\n13.2243851651398,11.7301672" +
            "100996\r\n13.2157857861553,11.6037491962988\r\n13.2041169829757,11.4777988564434\r\n13" +
            ".1896999104892,11.3519743024242\r\n13.1723842693523,11.2264460731799\r\n13.152256128" +
            "0342,11.1014294873121\r\n13.1293195179694,10.9769244274102\r\n13.1037038313134,10.85" +
            "29532192037\r\n13.0752798076639,10.729493598835\r\n13.0440110186341,10.6067391689694" +
            "\r\n13.010041558967,10.4847099161353\r\n12.9733246398385,10.3636012886894\r\n12.933770" +
            "1594865,10.2431963382808\r\n12.891731860069,10.1237565350052\r\n12.847081360033,10.0" +
            "052591976635\r\n12.8002676855563,9.88738825845673\r\n12.7520716741768,9.770281007106" +
            "13\r\n12.7031302480314,9.6532627525034\r\n12.6530927619696,9.53686762018136\r\n12.6022" +
            "820591298,9.42075827946718\r\n12.5505370416684,9.30510673642574\r\n12.4981478194599," +
            "9.1897688254443\r\n12.4451501462167,9.07455204818091\r\n12.3918020049191,8.959504962" +
            "54101\r\n12.33824582448,8.84464654433518\r\n12.2845261297136,8.7297791589419\r\n12.231" +
            "2115824969,8.61479506367883\r\n12.1781605914819,8.49967685528377\r\n12.1255126824022" +
            ",8.38444351922801\r\n12.073003199164,8.26905118720217\r\n12.0207692396656,8.15351969" +
            "665415\r\n11.9683934538804,8.03797057656157\r\n11.9162705555116,7.92247083922682\r\n11" +
            ".8644325921175,7.80682748117127\r\n11.8124622204855,7.69116205929026\r\n11.760790975" +
            "2785,7.57534649712282\r\n11.7092567857256,7.45955071370209\r\n11.657732078821,7.3437" +
            "5060074555\r\n11.6065017353421,7.22780255223372\r\n11.5554084579185,7.1118743393963\r" +
            "\n11.5044724442515,6.99577831420168\r\n11.4536711808654,6.87970315815979\r\n11.402906" +
            "7649439,6.7634328905165\r\n11.3523998290736,6.64720974933902\r\n11.3019297472543,6.5" +
            "307914987011\r\n11.2516922208374,6.41461017662469\r\n11.2016441046253,6.298067978896" +
            "17\r\n11.151573367999,6.18171457152042\r\n11.101694487337,6.06499921594867\r\n11.05205" +
            "042811,5.94851980310813\r\n11.0023086125607,5.83182431782357\r\n10.9528289226133,5.7" +
            "1517388675334\r\n10.9036437086256,5.59837541887996\r\n10.8543308293877,5.48155291831" +
            "302\r\n10.8053101670729,5.36458334372758\r\n10.756426401848,5.24763378580095\r\n10.707" +
            "6702650054,5.13070817845685\r\n10.65895087349,5.01358760087262\r\n10.6112030319064,4" +
            ".89624299187285\r\n10.5643237005172,4.77846042517628\r\n10.5188673229719,4.660137584" +
            "44855\r\n10.4746763267985,4.54144227325331\r\n10.4321900360719,4.42206289209565\r\n10." +
            "3918372257051,4.30187160665268\r\n10.3540021814344,4.18093793771215\r\n10.3185244845" +
            "801,4.05942937789621\r\n10.2851732794453,3.93710617396851\r\n10.2544573568778,3.8142" +
            "4305300489\r\n10.2261160779708,3.69079276200947\r\n10.2002913856662,3.56677261576207" +
            "\r\n10.1769481655506,3.44237496429589\r\n10.1558692696481,3.31735740388165\r\n10.13752" +
            "24491712,3.19219251316834\r\n10.1214282945715,3.0665951710442\r\n10.1081004826359,2." +
            "94065675948773\r\n10.0971158410663,2.81450285923879\r\n10.0888728076813,2.6881991405" +
            "08\r\n10.0829773505622,2.5616792667172\r\n10.0796604704206,2.43518047793145\r\n10.0788" +
            "224502898,2.3084878404892\r\n10.0805568337371,2.18181676613819\r\n10.0848426851458,2" +
            ".05535937872565\r\n10.0916997791584,1.92892330402576\r\n10.1008507960669,1.802657031" +
            "623\r\n10.1118978791009,1.67649530070454\r\n10.1224614297382,1.55043127794171\r\n10.13" +
            "27241502819,1.42410425190017\r\n10.1423702521615,1.29785961403481\r\n10.151299146153" +
            "7,1.17148501689514\r\n10.1594816669254,1.0451755315789\r\n10.1670780912584,0.9187611" +
            "66986515\r\n10.1732817671212,0.792305002987768\r\n10.1785053449203,0.665678584867185" +
            "\r\n10.1824178208652,0.539222742556387\r\n10.1850250704078,0.412546832399762\r\n10.186" +
            "4288688748,0.285865432448405\r\n10.1868804250541,0.159221495157455\r\n10.18663564436" +
            "01,0.032658555638766\r\n10.1857253328515,-0.0940162894755099\r\n10.1841218049606,-0." +
            "220609945398004\r\n10.1820955001398,-0.347271553813039\r\n10.1795272218427,-0.474022" +
            "537904485\r\n10.1763466811923,-0.60047670816026\r\n10.1726492351511,-0.7272125344969" +
            "25\r\n10.1687624993342,-0.853777772724541\r\n10.1644653981481,-0.980409230941829\r\n10" +
            ".1597329283468,-1.10691398062321\r\n10.154726413064,-1.23346282223739\r\n10.14931570" +
            "12882,-1.36007771505726\r\n10.1433474498947,-1.48658800711015\r\n10.1372375515902,-1" +
            ".61312023192872\r\n10.1306944840924,-1.73952554174119\r\n10.1236228753404,-1.8660190" +
            "4429435\r\n10.1164179374157,-1.99253470960998\r\n10.1087848058569,-2.11892364920906\r" +
            "\n10.1005932392149,-2.24520796398065\r\n10.0922972587455,-2.37170722012166\r\n10.0834" +
            "438239341,-2.49810192422567\r\n10.0742874561504,-2.62434751586884\r\n10.064869417808" +
            ",-2.75063748123709\r\n10.0549239085525,-2.87701573419716\r\n10.0445472135931,-3.0032" +
            "6709003203\r\n10.0340071731677,-3.12934778968655\r\n10.0230998941312,-3.255687447939" +
            "3\r\n10.0116001208862,-3.38172945632946\r\n10,-3.50798661272705")]
        public string Custom {
            get {
                return ((string)(this["Custom"]));
            }
            set {
                this["Custom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HeadingCorrection {
            get {
                return ((double)(this["HeadingCorrection"]));
            }
            set {
                this["HeadingCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double DualAntennaDistance {
            get {
                return ((double)(this["DualAntennaDistance"]));
            }
            set {
                this["DualAntennaDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastGuidanceLine {
            get {
                return ((int)(this["LastGuidanceLine"]));
            }
            set {
                this["LastGuidanceLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setComm_commName {
            get {
                return ((string)(this["setComm_commName"]));
            }
            set {
                this["setComm_commName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int setPort_baudRateGPS {
            get {
                return ((int)(this["setPort_baudRateGPS"]));
            }
            set {
                this["setPort_baudRateGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int setPort_baudRateGPS2 {
            get {
                return ((int)(this["setPort_baudRateGPS2"]));
            }
            set {
                this["setPort_baudRateGPS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setPort_portNameGPS2 {
            get {
                return ((string)(this["setPort_portNameGPS2"]));
            }
            set {
                this["setPort_portNameGPS2"] = value;
            }
        }
    }
}
