//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    public sealed partial class Vehicle : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vehicle defaultInstance = ((Vehicle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vehicle())));
        
        public static Vehicle Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_antennaHeight {
            get {
                return ((double)(this["setVehicle_antennaHeight"]));
            }
            set {
                this["setVehicle_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double setVehicle_antennaPivot {
            get {
                return ((double)(this["setVehicle_antennaPivot"]));
            }
            set {
                this["setVehicle_antennaPivot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double setVehicle_wheelbase {
            get {
                return ((double)(this["setVehicle_wheelbase"]));
            }
            set {
                this["setVehicle_wheelbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isPivotBehindAntenna {
            get {
                return ((bool)(this["setVehicle_isPivotBehindAntenna"]));
            }
            set {
                this["setVehicle_isPivotBehindAntenna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isSteerAxleAhead {
            get {
                return ((bool)(this["setVehicle_isSteerAxleAhead"]));
            }
            set {
                this["setVehicle_isSteerAxleAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vehicle - ")]
        public string setVehicle_vehicleName {
            get {
                return ((string)(this["setVehicle_vehicleName"]));
            }
            set {
                this["setVehicle_vehicleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_goalPointLookAhead {
            get {
                return ((double)(this["setVehicle_goalPointLookAhead"]));
            }
            set {
                this["setVehicle_goalPointLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public double setVehicle_maxAngularVelocity {
            get {
                return ((double)(this["setVehicle_maxAngularVelocity"]));
            }
            set {
                this["setVehicle_maxAngularVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double setVehicle_maxSteerAngle {
            get {
                return ((double)(this["setVehicle_maxSteerAngle"]));
            }
            set {
                this["setVehicle_maxSteerAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int set_youTurnDistance {
            get {
                return ((int)(this["set_youTurnDistance"]));
            }
            set {
                this["set_youTurnDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Ko {
            get {
                return ((byte)(this["setAS_Ko"]));
            }
            set {
                this["setAS_Ko"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Kp {
            get {
                return ((byte)(this["setAS_Kp"]));
            }
            set {
                this["setAS_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public byte setAS_lowSteerPWM {
            get {
                return ((byte)(this["setAS_lowSteerPWM"]));
            }
            set {
                this["setAS_lowSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Kd {
            get {
                return ((byte)(this["setAS_Kd"]));
            }
            set {
                this["setAS_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public byte setAS_steerAngleOffset {
            get {
                return ((byte)(this["setAS_steerAngleOffset"]));
            }
            set {
                this["setAS_steerAngleOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_minSteerPWM {
            get {
                return ((byte)(this["setAS_minSteerPWM"]));
            }
            set {
                this["setAS_minSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte setAS_highSteerPWM {
            get {
                return ((byte)(this["setAS_highSteerPWM"]));
            }
            set {
                this["setAS_highSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte setAS_countsPerDegree {
            get {
                return ((byte)(this["setAS_countsPerDegree"]));
            }
            set {
                this["setAS_countsPerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_FunctionEnter {
            get {
                return ((string)(this["seq_FunctionEnter"]));
            }
            set {
                this["seq_FunctionEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_FunctionExit {
            get {
                return ((string)(this["seq_FunctionExit"]));
            }
            set {
                this["seq_FunctionExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_ActionEnter {
            get {
                return ((string)(this["seq_ActionEnter"]));
            }
            set {
                this["seq_ActionEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_ActionExit {
            get {
                return ((string)(this["seq_ActionExit"]));
            }
            set {
                this["seq_ActionExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_DistanceEnter {
            get {
                return ((string)(this["seq_DistanceEnter"]));
            }
            set {
                this["seq_DistanceEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0,0")]
        public string seq_DistanceExit {
            get {
                return ((string)(this["seq_DistanceExit"]));
            }
            set {
                this["seq_DistanceExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Machine 1,Machine 2,Machine 3,Machine 4,Machine 5,Machine 6")]
        public string seq_FunctionList {
            get {
                return ((string)(this["seq_FunctionList"]));
            }
            set {
                this["seq_FunctionList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Turn Off,Turn On")]
        public string seq_ActionList {
            get {
                return ((string)(this["seq_ActionList"]));
            }
            set {
                this["seq_ActionList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.85")]
        public double setVehicle_minTurningRadius {
            get {
                return ((double)(this["setVehicle_minTurningRadius"]));
            }
            set {
                this["setVehicle_minTurningRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool set_youUseDubins {
            get {
                return ((bool)(this["set_youUseDubins"]));
            }
            set {
                this["set_youUseDubins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_antennaOffset {
            get {
                return ((double)(this["setVehicle_antennaOffset"]));
            }
            set {
                this["setVehicle_antennaOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double set_youTriggerDistance {
            get {
                return ((double)(this["set_youTriggerDistance"]));
            }
            set {
                this["set_youTriggerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double setVehicle_lookAheadDistanceFromLine {
            get {
                return ((double)(this["setVehicle_lookAheadDistanceFromLine"]));
            }
            set {
                this["setVehicle_lookAheadDistanceFromLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_lookAheadMinimum {
            get {
                return ((double)(this["setVehicle_lookAheadMinimum"]));
            }
            set {
                this["setVehicle_lookAheadMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double setVehicle_goalPointLookAheadUturnMult {
            get {
                return ((double)(this["setVehicle_goalPointLookAheadUturnMult"]));
            }
            set {
                this["setVehicle_goalPointLookAheadUturnMult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double set_geoFenceDistance {
            get {
                return ((double)(this["set_geoFenceDistance"]));
            }
            set {
                this["set_geoFenceDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setVehicle_stanleyGain {
            get {
                return ((double)(this["setVehicle_stanleyGain"]));
            }
            set {
                this["setVehicle_stanleyGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setVehicle_stanleyHeadingErrorGain {
            get {
                return ((double)(this["setVehicle_stanleyHeadingErrorGain"]));
            }
            set {
                this["setVehicle_stanleyHeadingErrorGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isStanleyUsed {
            get {
                return ((bool)(this["setVehicle_isStanleyUsed"]));
            }
            set {
                this["setVehicle_isStanleyUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tool - ")]
        public string setVehicle_toolName {
            get {
                return ((string)(this["setVehicle_toolName"]));
            }
            set {
                this["setVehicle_toolName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Env")]
        public string setVehicle_envName {
            get {
                return ((string)(this["setVehicle_envName"]));
            }
            set {
                this["setVehicle_envName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setVehicle_vehicleType {
            get {
                return ((int)(this["setVehicle_vehicleType"]));
            }
            set {
                this["setVehicle_vehicleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int set_youSkipWidth {
            get {
                return ((int)(this["set_youSkipWidth"]));
            }
            set {
                this["set_youSkipWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_setting1 {
            get {
                return ((byte)(this["setArdSteer_setting1"]));
            }
            set {
                this["setArdSteer_setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte setArdSteer_minSpeed {
            get {
                return ((byte)(this["setArdSteer_minSpeed"]));
            }
            set {
                this["setArdSteer_minSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setArdSteer_maxSpeed {
            get {
                return ((byte)(this["setArdSteer_maxSpeed"]));
            }
            set {
                this["setArdSteer_maxSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public byte setArdSteer_setting0 {
            get {
                return ((byte)(this["setArdSteer_setting0"]));
            }
            set {
                this["setArdSteer_setting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_hydraulicLiftLookAhead {
            get {
                return ((double)(this["setVehicle_hydraulicLiftLookAhead"]));
            }
            set {
                this["setVehicle_hydraulicLiftLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setVehicle_isMachineControlToAutoSteer {
            get {
                return ((bool)(this["setVehicle_isMachineControlToAutoSteer"]));
            }
            set {
                this["setVehicle_isMachineControlToAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_inclinometer {
            get {
                return ((byte)(this["setArdSteer_inclinometer"]));
            }
            set {
                this["setArdSteer_inclinometer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setArdSteer_maxPulseCounts {
            get {
                return ((byte)(this["setArdSteer_maxPulseCounts"]));
            }
            set {
                this["setArdSteer_maxPulseCounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setArdMac_hydRaiseTime {
            get {
                return ((byte)(this["setArdMac_hydRaiseTime"]));
            }
            set {
                this["setArdMac_hydRaiseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte setArdMac_hydLowerTime {
            get {
                return ((byte)(this["setArdMac_hydLowerTime"]));
            }
            set {
                this["setArdMac_hydLowerTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdMac_isHydEnabled {
            get {
                return ((byte)(this["setArdMac_isHydEnabled"]));
            }
            set {
                this["setArdMac_isHydEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setTool_defaultSectionWidth {
            get {
                return ((double)(this["setTool_defaultSectionWidth"]));
            }
            set {
                this["setTool_defaultSectionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte setArdSteer_ackermanFix {
            get {
                return ((byte)(this["setArdSteer_ackermanFix"]));
            }
            set {
                this["setArdSteer_ackermanFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdMac_setting0 {
            get {
                return ((byte)(this["setArdMac_setting0"]));
            }
            set {
                this["setArdMac_setting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setArdSteer_setting2 {
            get {
                return ((byte)(this["setArdSteer_setting2"]));
            }
            set {
                this["setArdSteer_setting2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<ToolSettings> ToolSettings {
            get {
                if ((this["ToolSettings"]) == null) (this["ToolSettings"]) = new System.Collections.Generic.List<ToolSettings>() { new ToolSettings() { Sections = { new double[] { -4.415, -1.415, 0 }, new double[] { -1.5, 1.5, 4 }, new double[] { 1.415, 4.415, 0 } } } };
                return ((global::System.Collections.Generic.List<ToolSettings>)(this["ToolSettings"]));
            }
            set {
                this["ToolSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.83")]
        public double GuidanceWidth {
            get {
                return ((double)(this["GuidanceWidth"]));
            }
            set {
                this["GuidanceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.085")]
        public double GuidanceOverlap {
            get {
                return ((double)(this["GuidanceOverlap"]));
            }
            set {
                this["GuidanceOverlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GuidanceOffset {
            get {
                return ((double)(this["GuidanceOffset"]));
            }
            set {
                this["GuidanceOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchManual {
            get {
                return ((bool)(this["setF_IsWorkSwitchManual"]));
            }
            set {
                this["setF_IsWorkSwitchManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchEnabled {
            get {
                return ((bool)(this["setF_IsWorkSwitchEnabled"]));
            }
            set {
                this["setF_IsWorkSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchActiveLow {
            get {
                return ((bool)(this["setF_IsWorkSwitchActiveLow"]));
            }
            set {
                this["setF_IsWorkSwitchActiveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"if ((this[""ToolSettings""]) == null) (this[""ToolSettings""]) = new System.Collections.Generic.List<ToolSettings>() { new ToolSettings() { Sections = { new double[] { -6.25, -3.05, 4 }, new double[] { 3.05, 6.25, 4 }, new double[] { -3.9, -0.7, 0 }, new double[] { 0.7, 3.9, 0 } } } };")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
